version: '3'
services:
  postgres:
    container_name: barberShopPg
    image: postgres:latest
    ports:
      - '5052:5432'
    volumes:
      - /data/postgres:/data/postgres
    env_file:
      - docker-compose.env
    networks:
      - postgres-wapp

networks:
  postgres-wapp:
    driver: bridge
